import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import '@mantine/core/styles.css';
import "../../app/globals.css";
import { Toaster } from "react-hot-toast";
import ContextProvider from "@/context/ContextProvider";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${inter.className} w-full`}>
        <ContextProvider>
          <MantineProvider>
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
            <Layout >
              {children}
            </Layout>
          </MantineProvider>
        </ContextProvider>
      </body>
    </html>
  );
}