import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { MantineProvider } from "@mantine/core";
import '@mantine/core/styles.css';
import "../../app/globals.css";
import Provider from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import getUserSession from "@/helper/getUserSession";
import ContextProvider from "@/context/ContextProvider";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getUserSession()

  async function getAuthUser() {
    const res = await fetch("http://localhost:3000/api/authUser", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(session.user)
    })
    const data = await res.json()
    if(!data){
      return null;
    }
    return data
  }
  const authUser = getAuthUser()

  return (
    <html lang="en">
      <body className={`${inter.className} w-full`}>
        <ContextProvider>
          <Provider>
            <MantineProvider>
              <Toaster
                position="top-center"
                reverseOrder={false}
              />
              <Layout authUser={authUser}>
                {children}
              </Layout>
            </MantineProvider>
          </Provider>
        </ContextProvider>
      </body>
    </html>
  );
}