import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/components/NextUiProvider";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextUiProvider>
          <main className="bg-light min-h-[100vh] flex md:flex-row flex-col w-full relative">
            <Sidebar />
            <div className="flex-1 max-w-full overflow-hidden">
              {children}
            </div>
          </main>
        </NextUiProvider>
      </body>
    </html>
  );
}